# Generated by Django 4.0.1 on 2022-12-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('resourceId', models.CharField(max_length=300)),
                ('start_time', models.CharField(max_length=300)),
                ('end_time', models.CharField(max_length=300)),
            ],
        ),
    ]
